# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368adaa57adc0187b9c013a482a94cd7623b82e2c02e9b3ac734f4a0d571b08d5e45c040d64e292afbd9ff3b9e15141036edce4e4ec44e0b6d9586637254ae3d

test:
  secret_key_base: 4415f44eb9709efb152e8950d802e91e41712b17dbd2681546a82abb0b77a614b4efe78c340d21ed5804202e902cb831a47c3c4f08034549506e34c45f8de370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
